### ISSUE TITLE
Can batch_translate_text in the following code support using glossary config?

### ISSUE THREAD

**Issue by Oscarjia** [googleapis/python-translate#142]
hi, I have a question that needs your help.

As the link [Use glossaries](https://cloud.google.com/translate/docs/advanced/glossary#use_glossaries)
and the link [Batch request](https://cloud.google.com/translate/docs/advanced/batch-translation#batch-request)
said.

Can batch_translate_text in the following code support using glossary config? If yes, where i config the glossary?
thanks.

`from google.cloud import translate
def batch_translate_text(
    input_uri="gs://YOUR_BUCKET_ID/path/to/your/file.txt",
    output_uri="gs://YOUR_BUCKET_ID/path/to/save/results/",
    project_id="YOUR_PROJECT_ID",
    timeout=180,
):
    """Translates a batch of texts on GCS and stores the result in a GCS location."""

    client = translate.TranslationServiceClient()

    location = "us-central1"
    # Supported file types: https://cloud.google.com/translate/docs/supported-formats
    gcs_source = {"input_uri": input_uri}

    input_configs_element = {
        "gcs_source": gcs_source,
        "mime_type": "text/plain",  # Can be "text/plain" or "text/html".
    }
    gcs_destination = {"output_uri_prefix": output_uri}
    output_config = {"gcs_destination": gcs_destination}
    parent = f"projects/{project_id}/locations/{location}"

    # Supported language codes: https://cloud.google.com/translate/docs/language
    operation = client.batch_translate_text(
        request={
            "parent": parent,
            "source_language_code": "en",
            "target_language_codes": ["ja"],  # Up to 10 language codes here.
            "input_configs": [input_configs_element],
            "output_config": output_config,
        }
    )
    print("Waiting for operation to complete...")
    response = operation.result(timeout)
    print("Total Characters: {}".format(response.total_characters))
    print("Translated Characters: {}".format(response.translated_characters))`

**Comment by munkhuushmgl** [comment]
Hello @Oscarjia 

I think you have already the answer in the docs
https://cloud.google.com/translate/docs/advanced/batch-translation#batch-glossary

https://github.com/googleapis/python-translate/blob/master/samples/snippets/translate_v3_batch_translate_text_with_glossary.py

**Comment by munkhuushmgl** [comment]
With that note, I am closing this issue, since this is not library related issue.
