### ISSUE TITLE
Why batch translate with glossary output two results file?

### ISSUE THREAD

**Issue by Oscarjia** [googleapis/python-translate#155]
hi, Can anyone give me some help?

As i try this code in the link [batch-translate-with glossary](https://cloud.google.com/translate/docs/samples/translate-v3-batch-translate-text-with-glossary#code-sample)

I found it will output two results file:
one is  glossary_translations.txt  and the other is translations.txt
why this happen? Can  I only output glossary translation file? Will translator charge me twice?

>  from google.cloud import translate
> 
> def batch_translate_text_with_glossary(
>     input_uri="gs://YOUR_BUCKET_ID/path/to/your/file.txt",
>     output_uri="gs://YOUR_BUCKET_ID/path/to/save/results/",
>     project_id="YOUR_PROJECT_ID",
>     glossary_id="YOUR_GLOSSARY_ID",
>     timeout=320,
> ):
>    client = translate.TranslationServiceClient()
>     # Supported language codes: https://cloud.google.com/translate/docs/languages
>     location = "us-central1"
>     # Supported file types: https://cloud.google.com/translate/docs/supported-formats
>     gcs_source = {"input_uri": input_uri}
>     input_configs_element = {
>         "gcs_source": gcs_source,
>         "mime_type": "text/plain",  # Can be "text/plain" or "text/html".
>     }
>     gcs_destination = {"output_uri_prefix": output_uri}
>     output_config = {"gcs_destination": gcs_destination}
>     parent = f"projects/{project_id}/locations/{location}"
>     # glossary is a custom dictionary Translation API uses
>     # to translate the domain-specific terminology.
>     glossary_path = client.glossary_path(
>         project_id, "us-central1", glossary_id  # The location of the glossary
>     )
>     glossary_config = translate.TranslateTextGlossaryConfig(glossary=glossary_path)
>     glossaries = {"ja": glossary_config}  # target lang as key
>     operation = client.batch_translate_text(
>         request={
>             "parent": parent,
>             "source_language_code": "en",
>             "target_language_codes": ["ja"],  # Up to 10 language codes here.
>             "input_configs": [input_configs_element],
>             "glossaries": glossaries,
>             "output_config": output_config,
>         }
>     )
>     print("Waiting for operation to complete...")
>     response = operation.result(timeout)
>     print("Total Characters: {}".format(response.total_characters))
>     print("Translated Characters: {}".format(response.translated_characters))

**Comment by Oscarjia** [comment]
@munkhuushmgl 
hi munkhuushmgl , thank you for your quick response.

Actually, i find  the output two files all were translated. 
one file is with glossary on the file name like: glossary_translations.txt and the other is only translation on the file，like: translations.txt.
So, my question is this way is the original design or some problems? 
Actually i think i only need the file with glossary ,because i use the batch translate with glossary method.
thanks.

**Comment by munkhuushmgl** [comment]
I do not think there is a problem.

Further design and details about batch translate with glossary:

https://cloud.google.com/translate/docs/reference/rest/v3/projects.locations/batchTranslateText#OutputConfig



Further question about billing and how it charges, please refer to the following document:
https://cloud.google.com/translate/pricing
For questions about billing, he should read this document:

https://cloud.google.com/translate/docs/billing-questions



With this note, I am closing this issue since there is nothing related to client library.

**Comment by Oscarjia** [comment]
thanks @munkhuushmgl
