### ISSUE TITLE
Text removed from Traditional Chinese to Simplified Chinese translations when using HTML formatting

### ISSUE THREAD

**Issue by SharmaineLim** [googleapis/python-translate#233]
When I try to translate HTML text from Traditional Chinese to Simplified Chinese (or vice versa), any text after an HTML tag is not returned in the response (or the HTML tag is not returned, etc.).

Basically, some text is missing from the response.

This didn't happen when I tried translating to/from English or Japanese.

#### Environment details

  - OS type and version: macOS Big Sur, version 11.4
  - Python version: 3.8.8
  - pip version: 21.0.1
  - `google-cloud-translate` version: 3.2.1

#### Steps to reproduce

  1. Import `google.cloud.translate`
  2. Send a translate request, from Traditional Chinese to Simplified Chinese (or vice versa)
  3. Print both input and output

#### Code example

```python
from google.cloud import translate

source_language_code = "zh-TW"  # Traditional Chinese
target_language_code = "zh-CN"  # Simplified Chinese
contents = ["敏捷的<b>棕</b>色狐狸跳過了懶狗。"]

project_id = "my-project-id"
location = "global"

client = translate.TranslationServiceClient()
response = client.translate_text(
    request={
        "parent": f"projects/{project_id}/locations/{location}",
        "contents": contents,
        "mime_type": "text/html",
        "source_language_code": source_language_code,
        "target_language_code": target_language_code,
    }
)

print(contents[0])
# 敏捷的<b>棕</b>色狐狸跳過了懶狗。

print(response.translations[0].translated_text)
# 敏捷的
```

Also tried with `<strong>`, `<i>`, `<a>`, `<span>` and `<br>`, and those return missing text (or missing HTML tags, which doesn't match up with the usual response).

#### Stack trace
N/A (no error)

**Comment by SharmaineLim** [comment]
I tried using `"mime_type": "text/plain"` as a workaround and it seems to work.

```
敏捷的<b>棕</b>色狐狸跳過了懶狗。
敏捷的<b>棕</b>色狐狸跳过了懒狗。

敏捷的<a href="https://google.com/">棕</a>色狐狸跳過了懶狗。
敏捷的<a href="https://google.com/">棕</a>色狐狸跳过了懒狗。

敏捷的棕<br/>色狐狸跳過了懶狗。
敏捷的棕<br/>色狐狸跳过了懒狗。
```

**Comment by orionnye** [comment]
Hey @SharmaineLim! Thank you so much for bringing this to our attention, I reproduced the bug and confirmed this is an issue with the translation service rather than the sample code we have in this repository. I'd recommend filing a bug report here: https://issuetracker.google.com/issues/new?component=187144&template=0
