### ISSUE TITLE
Google Translate with AWS lambda

### ISSUE THREAD

**Issue by Mkamal88** [googleapis/python-translate#288]
I'm trying to deploy a software that translate using google translate on AWS lambda, I got the following error when I tried to fire the lambda:
`Runtime.ImportModuleError: Unable to import module 'lambda_function': cannot import name 'cygrpc' from 'grpc._cython'`

I'm using Python 3.9
and I uploaded the package with all it's dependences according to the environment.

**Comment by kweinmeister** [comment]
@Mkamal88 - did any of the suggestions help resolve your issue?

**Comment by Mkamal88** [comment]
It worked with me when I created the requirements.txt again and installed it on Linux OS
