### ISSUE TITLE
Remove the Watermark at the top of the translated pdfs

### ISSUE THREAD

**Issue by AnupJoseph** [googleapis/python-translate#295]
### Problem

I am using the [advanced Translation API](https://cloud.google.com/translate/docs/advanced/translate-documents#python) Python client for document translation. The API performance is amazing :rocket: so I wanted to say thanks for that.

The API however add this Machine Translated By Google watermark at the top of every page. This is a deal breaker for my clients. Current I have two options to resolve this:

- Crop the top x % of the pdfs
- Replace the string by doing a text search and replace in the pdfs

However I don't really like any of these solutions. I searched through the documentation but couldn't find a way to stop this watermark in the first place. Any suggested would be appreciated.

Thanks for the API!

**Comment by galz10** [comment]
Hi @AnupJoseph , could you share your code so i could reproduce this issue.

**Comment by AnupJoseph** [comment]
Hi @galz10 , the code I am using is from the [Advanced Translation API](https://cloud.google.com/translate/docs/advanced/translate-documents#python) here.
```py
def translate_document(project_id: str = " ", file_path: str = "",language:str="",doctype:str="application/pdf"):

    client = translate.TranslationServiceClient()

    location = "us-central1"

    parent = f"projects/{project_id}/locations/{location}"
    with open(file_path, "rb") as document:
        document_content = document.read()

    document_input_config = {
        "content": document_content,
        "mime_type": doctype,
    }

    response = client.translate_document(
        request={
            "parent": parent,
            "target_language_code": language,
            "document_input_config": document_input_config,
        }
    )
    with open("output.pdf","wb") as file:
        out_file.write(response.document_translation.byte_stream_outputs[0])
```
On running this over any file this is the output produced
![Instructions-for-Cloud-Computing-Lab-Journal-Submissions-1-pdf](https://user-images.githubusercontent.com/43500348/141064852-06579da4-0a01-4a3b-9949-3bdf4fe73968.png)
I basically wanted to remove the watermark ** Machine Translated By Google** in the example. Our client doesn't want it in the output. I looked through the docs but couldn't any options for that

**Comment by kweinmeister** [comment]
Hi @AnupJoseph, here are some links that can provide you more detail on your question:
* https://support.google.com/translate/thread/115298680/how-to-remove-machine-translated-by-google
* https://stackoverflow.com/questions/67645265/remove-machine-translated-by-google

As this is issue is not specific to the Python API layer that this repo supports, I will go ahead and close this issue. If you have any more questions about the policy, please feel free to reach out to [Google Cloud Support](https://cloud.google.com/support).
