### ISSUE TITLE
Multiple translations for ambiguously gendered inputs

### ISSUE THREAD

**Issue by ranjita-naik** [googleapis/python-translate#327]
Does the translate API return multiple translations for ambiguous inputs (https://ai.googleblog.com/2020/04/a-scalable-approach-to-reducing-gender.html)? For instance, while translating 'awesome' from English to Spanish,  https://translate.google.co.in/ returns two translations as shown below.  Is this feature supported in the API as well?

![image](https://user-images.githubusercontent.com/32549868/150790727-7af190f7-e947-4ef8-a98a-141d7c69b0b6.png)

thanks,
Ranjita

**Comment by kweinmeister** [comment]
Hi, this repo is specifically for issues with the Python client library, and is not staffed for general usage questions with the Cloud Translation service.

From what I see in this [post](https://groups.google.com/g/google-translate-api/c/zcqiloAZGZs/m/HxwC07OiAgAJ), that feature is currently not supported. For more information, I suggest using the [developer forum](https://groups.google.com/g/google-translate-api). Thanks!

**Comment by ranjita-naik** [comment]
@kweinmeister - thank you for the clarification!

Best,
Ranjita
