### ISSUE TITLE
Weird text encoding returned in v2 translation

### ISSUE THREAD

**Issue by kuhanaklobasa** [googleapis/python-translate#330]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS type and version: Mac OS Big Sur 11.6.2
  - Python version: 3.9.6
  - pip version: 21.2.4
  - `google-cloud-translate` version: 2.0.1

#### Steps to reproduce

Try and translate text?

#### Code example

```python
translate_credentials = service_account.Credentials.from_service_account_file('secret.json') 
translate_client = translate.Client(credentials=translate_credentials)
result = translate_client.translate(text, target_language=target)
return print("**Translated text:** "  + result['translatedText'])
```

#### Stack trace
No traceback

I tried translating  "Any more issues?" and I got "D&#39;autres problèmes ?"
If I tried to UTF-8 encode the returned string I got "b'D&#39;autres probl\xc3\xa8mes\xc2\xa0?'"

**Comment by kweinmeister** [comment]
Hi, can you please also include the code you used to UTF-8 encode the string for a full code sample? Thanks.

**Comment by kuhanaklobasa** [comment]
> 

I used the python encode() method

**Comment by kuhanaklobasa** [comment]
Any update on this?

**Comment by kweinmeister** [comment]
The characters you are seeing when encoding look correct. Any non-ASCII characters that require more than one byte, such as the è,  will be displayed as their hex UTF-8 code units. The `\xc2\xa0` sequence at the end is a non-breaking space. For more information, please see: https://realpython.com/python-encodings-guide/#encoding-and-decoding-in-python-3

**Comment by kweinmeister** [comment]
I will go ahead and close this issue. If you have any more information that suggests there's a bug in the client library, please feel free to reopen. Thanks!
