### ISSUE TITLE
Google Cloud Translation - Glossaries - Failed to Initialize Glossary

### ISSUE THREAD

**Issue by HAtheDataScientist** [googleapis/python-translate#337]
I'm facing an issue while translating the text with glossary.
I have gave the IAM roles and permissions of cloud translation, cloud storage, AutoML -- All Admin Access, still facing the issue while translating. 
![Screenshot (586)](https://user-images.githubusercontent.com/97654061/154918103-2c85ac1b-8ea8-48cd-82e0-8626ab8b0608.png)
![Screenshot (587)](https://user-images.githubusercontent.com/97654061/154918108-2495eeec-c381-4a11-96e7-0fcd4e82ab61.png)

I'm using the custom glossary to translate.
What I should specify in the glossary_config?

**Comment by kweinmeister** [comment]
To troubleshoot, I might suggest starting with the [create glossary sample](https://github.com/googleapis/python-translate/blob/HEAD/samples/snippets/translate_v3_create_glossary.py), and then trying to access that same resource with the sample code you're using.

**Comment by parthea** [comment]
I'm going to close this issue due to inactivity but please feel free to re-open or create a new issue.
