### ISSUE TITLE
how can i use the python-translate api with proxy param

### ISSUE THREAD

**Issue by Oscarjia** [googleapis/python-translate#80]
hello everyone,
  i have question, can i get help from anyone of you?

  my running environment network is behind the proxy. So where can i config every request is with proxy param?

**Comment by munkhuushmgl** [comment]
Could you share the following requests?

(1) Python version. python --version

(2) OS

(3) Open SSL version. python -c "import ssl; print ssl.OPENSSL_VERSION"

(4) Versions of the following packages. (A full pip freeze is also fine.)
```
google-cloud-translate
google-api-core
google-auth
requests
grpcio
```

**Comment by Oscarjia** [comment]
@munkhuushmgl 
   hi, my environment is as below:
   (1) Python version. python --version
        **Python 3.7.6**
   (2) OS
        **Windows**
   (3) Open SSL version. python -c "import ssl; print ssl.OPENSSL_VERSION"
        **OpenSSL 1.1.1g  21 Apr 2020**
   (4)
       google-cloud-translate=3.0.1
       google-api-core=1.23.0
       google-auth=1.23.0
       requests=2.25.0
       grpcio=1.29.0

Actually, i want to know how to  realize  the requset through proxy, without setting the global env like http_proxy or https_proxy.

**Comment by munkhuushmgl** [comment]
@busunkim96 Can you help me out? (my proxy knowledge is very shallow)

**Comment by busunkim96** [comment]
Hi @Oscarjia,

The python libraries do not have any built in support for proxies. https://medium.com/google-cloud/accessing-google-cloud-apis-though-a-proxy-fe46658b5f2a has a good high level overview. The TLDR; is that you will need to set the `http_proxy` and `https_proxy` environment variables.

**Comment by munkhuushmgl** [comment]
@busunkim96 Thanks a lot!
