### ISSUE TITLE
translate_text() got an unexpected keyword argument 'request'

### ISSUE THREAD

**Issue by 08tjlys** [googleapis/python-translate#87]
hi,
    i am using v3 interface, i referred to the sample code on the document and my code is like following
    did i do something wrong? really appreciate your help

  
    client = translate.TranslationServiceClient(credentials="XXXX.json")
    location = "global"
    project_id="XXXXX"
    parent = f"projects/{project_id}/locations/{location}"

    # Detail on supported types can be found here:
    # https://cloud.google.com/translate/docs/supported-formats
    response = client.translate_text(
        request={
            "parent": parent,
            "contents": [content],
            "mime_type": "text/plain",  # mime types: text/plain, text/html
            "source_language_code": "zh-cn",
            "target_language_code": "en",
        }
    )

    # Display the translation for each input text provided
    for translation in response.translations:
        print("Translated text: {}".format(translation.translated_text))

**Comment by munkhuushmgl** [comment]
@08tjlys Could you share the version of google.cloud.translate?

**Comment by 08tjlys** [comment]
hi, 
so sorry for the troublesome,i realized it was because version of my google-cloud-translate was still for basic version, i didn't upgrade it successfully using  
 `pip install --upgrade google-cloud-translate`  
now it is normal after i upgraded the library, sorry again
