### ISSUE TITLE
Tests hang after first test under Python 3.8

### ISSUE THREAD

**Issue by buschmann23** [googleapis/python-translate#99]
When trying to build rpm packages of google-cloud-translate for different releases of openSUSE, the test suite hangs on the first test when Python 3.8.6 is used. On older versions of Python, like 3.6.10, the tests run fine.

#### Environment details

  - OS type and version: Linux / openSUSE Tumbleweed
  - Python version: 3.8.6
  - `google-cloud-translate` version: 3.0.2
  - `google-api-core` version: 1.24.1
  - `google-auth` version: 1.24.0
  - `requests` version: 2.25.1
  - `grpcio` version: 1.34.0

#### Steps to reproduce

Installation is not done via pip but via setup.py:

  1. `/usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'`
  2. `/usr/bin/python3 setup.py install -O1 --skip-build --force --root /home/abuild/rpmbuild/BUILDROOT/python-google-cloud-translate-3.0.2-0.x86_64 --prefix /usr`
  3. Running the tests:
```
PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-google-cloud-translate-3.0.2-0.x86_64/usr/lib/python3.8/site-packages
PYTHONDONTWRITEBYTECODE=1
pytest-3.8 --ignore=_build.python2 --ignore=_build.python3 --ignore=_build.pypy3 -v tests/unit -k 'not test_extra_headers'
============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/abuild/rpmbuild/BUILD/google-cloud-translate-3.0.2
plugins: asyncio-0.14.0
collecting ... collected 240 items / 1 deselected / 239 selected

tests/unit/gapic/translate_v3/test_translation_service.py::test__get_default_mtls_endpoint PASSED [  0%]
```
Then the tests hang forever and one CPU core is used 100%.

**Comment by busunkim96** [comment]
Thanks for the report!

I took a look at the second test and nothing in it particularly stands out. https://github.com/googleapis/python-translate/blob/b964066146fababea506945017e415e5aa100a99/tests/unit/gapic/translate_v3/test_translation_service.py#L100-L112 

Does 3.7 also work as expected? 

And if it's not too much trouble, could you also try with 3.9?

**Comment by buschmann23** [comment]
Sorry for this late reply. I now at least tested it with Python 3.6 on openSUSE Tumbleweed, where the tests failed with Python 3.8 before. They have the same issue there as described in my opening post. So the issue seems not to be differences between Python 3.6 and 3.8. Seems there is some other difference in the/my environment.

**Comment by buschmann23** [comment]
Not sure what changed in the build environment, but tests are now running fine.
